### ISSUE TITLE
Python games - Pygame

### ISSUE THREAD

**Issue by mblayman** [python-frederick/talks#10]
If you want to make a game in Python, what tools could you use? Pygame is one option. What other ways could a game be made?

**Comment by mblayman** [comment]
I'm checking with the Frederick Game Development meetup to see if we can do this one jointly. I'm not aware of someone who knows Pygame, but perhaps there is someone in that group.

**Comment by mblayman** [comment]
@naegelejd, thanks for volunteering! We need to find a date that will work for you, Python Frederick, and the Frederick Game Development Meetup. @jcromartie, we chatted about using the Python meetups 2nd Wednesday timeslot. There are already a couple of meetups scheduled so the next free slots are 8/10, 9/14, and 10/12 (and so on). What date would you guys be ok with?

**Comment by naegelejd** [comment]
I think 10/12 is best for me but I'm pretty flexible

**Comment by mblayman** [comment]
@naegelejd I got confirmation from @jcromartie via Meetup that 10/12 will be a good date to go with. I'll add it to the Python Frederick calendar.

**Comment by naegelejd** [comment]
Confirmed, thanks!

**Comment by mblayman** [comment]
I've put this event on the Python Frederick calendar. http://www.meetup.com/python-frederick/events/231401821/

**Comment by mblayman** [comment]
@naegelejd, the room for today's presentation only has a VGA hookup. I'm trying to get that resolved permanently, but if you have a VGA adapter that you can use for your machine, that would be awesome to bring.

**Comment by naegelejd** [comment]
No problem I'll bring one.

**Comment by mblayman** [comment]
Oops, closing this one out slipped off my radar. I forgot to send out a follow-up email after the event. I'll try to remember to mention the materials posted today. Thanks @naegelejd for presenting.
