### ISSUE TITLE
AWS SDK boto/boto3

### ISSUE THREAD

**Issue by patrickpierson** [python-frederick/talks#15]
I would be interested in doing a talk on boto/boto3 or listening to someone a lot smarter than me give one.

https://aws.amazon.com/sdk-for-python/

**Comment by patrickpierson** [comment]
@mblayman I added my boto3 talk as a submodule to the talks repo.  what is your thought on that? if dumb i can redo it.

**Comment by mblayman** [comment]
I think it's fine. Some people won't understand, but clicking on the link in the web UI takes them to the other repo so I'm sure they can figure it out without too much trouble.

**Comment by mblayman** [comment]
Do you mind leaving this open until after the talk? I like to have it as a reminder to send out a final email with links to the material after the talk.

**Comment by mblayman** [comment]
Thanks @patrickpierson! I appreciated the talk this evening.
