### ISSUE TITLE
SaltStack

### ISSUE THREAD

**Issue by mblayman** [python-frederick/talks#16]
@patrickpierson is giving a talk in March about SaltStack. I think this is a sub-talk from #4. We could do a counter talk on Ansible, then finish off the series by doing a comparison talk.

I might be qualified soon to give an Ansible talk as I spend more time building out my own infrastructure on a side project using Ansible.

Then Patrick and I can go head-to-head in a battle royale. :rage1: :wink:

**Comment by patrickpierson** [comment]
I am up for a battle royale.  Its going to be hard to beat me with the things I am bringing to the table.

That being said here is my draft plan for the talk:
1. What is SalkStack
2. Quick howto on getting Salt Master and Minion up and running
3. Write a few Salt states and jinja templates and deploy them against a Minion.

**Comment by patrickpierson** [comment]
updated with https://github.com/python-frederick/talks/commit/82dfff29eb1a6c44b94561a5d6d7728d416f2f54
