### ISSUE TITLE
Jupyter notebooks

### ISSUE THREAD

**Issue by mblayman** [python-frederick/talks#21]
Jupyter notebooks are awesome for working interactively with Python. It would make for a great talk.

**Comment by Jaredk** [comment]
I wholeheartedly agree. Also, I'm plenty flexible.  Sept-Dec, anytime is fine. Maybe let me know when you fill the other time slots, and I can work on this in the meantime.

**Comment by mblayman** [comment]
Among the three slots for the rest of the year (Sept., Nov., Dec.), I don't have any other speakers lined up. Would you be comfortable speaking in September? I'm working with FCC to meet there in September and Jupyter notebooks would be an *awesome* subject for students who might show up.

**Comment by mblayman** [comment]
One of the attendees of tonight's event suggested we have a talk on Jupyter notebooks. I think there is some interest here. 😄 

@Jaredk, any thoughts on a good month fit for you?

**Comment by Jaredk** [comment]
I can do september. Still offering flexibility on that.

**Comment by mblayman** [comment]
http://www.meetup.com/python-frederick/events/232767269/

**Comment by mblayman** [comment]
Hey there, @Jaredk! Are you still good for the talk tomorrow? I want to check to avoid any last minute scrambling in case something came up.

**Comment by mblayman** [comment]
@Jaredk, could you make your slides available in some manner so I can share them with the group? I'll send out a note to the mailing list after that.
