### ISSUE TITLE
Django channels and WebSockets

### ISSUE THREAD

**Issue by mblayman** [python-frederick/talks#23]
We'd like to do a talk on Django channels and @jcarbaugh has agreed to give such a talk at some point in the future. We need to hammer out the date that works best.

**Comment by jcarbaugh** [comment]
Per our Meetup thread, Dec 14th works great for me.

**Comment by mblayman** [comment]
Awesome, thanks for the confirmation. I'll add the topic to Meetup.

**Comment by mblayman** [comment]
We're go for launch. 😄 http://www.meetup.com/python-frederick/events/233037557/

**Comment by mblayman** [comment]
@jcarbaugh, we're quite a few months down the road from when we first wrote. Is December 14th still going to work for you to give your Django Channels presentation?

**Comment by jcarbaugh** [comment]
@mblayman yes! The 14th is still great for me.

**Comment by mblayman** [comment]
Excellent. I'm looking forward to it.

**Comment by mblayman** [comment]
@jcarbaugh Here's a couple of logistical notes for tonight's event.

Parking on Cowork Frederick's street (E. Patrick St.) should be free by the time of day you would arrive. If you can't find a spot on the street, the Carroll Creek parking garage is only a block away. Parking is super cheap (especially compared to DC) and would run you about $2-$4.

I'm planning to get to Cowork between 6-6:15. The doors should be open when you get there whether I've arrived or not. We meet in a large room on the first floor which is a straight walk back as soon as you enter.

**Comment by jcarbaugh** [comment]
@mblayman thanks for the info! I'm going to leave Gaithersburg around 4:30 just to make sure traffic up to Frederick works out. See you tonight!

**Comment by mblayman** [comment]
Cool. If you get in town early, there is a TechFrederick networking event at 19 E Church Street that starts at 5 that I'm sure you can crash. They'll have food there so that's where I'm planning to be from 5-6 😄 http://www.techfrederick.org/calendar/events/view/24

**Comment by mblayman** [comment]
@jcarbaugh thanks again for speaking tonight! Would you be able to share your presentation material? You could either add it to this repo or relay me some information and I could take care of it.

**Comment by mblayman** [comment]
Final wrap up about the meetup was posted to the list.
