### ISSUE TITLE
Django Wagtail

### ISSUE THREAD

**Issue by mblayman** [python-frederick/talks#28]
@devonwarren Would you be interested in giving a talk on Wagtail in February (the 8th) or March (the 8th)? If not those months, perhaps some other month?

**Comment by devonwarren** [comment]
Yeah I could do that, life has been a bit hectic but I'll try to fit in some time to go into more of the features and come up with a presentation. Will get back to you on timeline but I'm pretty sure I could fit it in before Feb

**Comment by mblayman** [comment]
Cool. I definitely don't want to pressure you if life is too crazy at the moment. We can chat at some time in the future and find a time that would work well for you. Thanks for your willingness to present!

**Comment by mblayman** [comment]
@devonwarren are you game for Feb. 8th? If not, @patrickpierson has a talk topic that he's willing to do for February so there's no pressure.

**Comment by devonwarren** [comment]
Hey @mblayman, actually if @patrickpierson could do Feb that would be good and I'll be good for March for sure

**Comment by patrickpierson** [comment]
sounds good to me

**Comment by mblayman** [comment]
@devonwarren I'll post Django Wagtail as the topic for March. Patrick is lined up to talk about Troposphere in February.

Do you have any summary that you'd like to use for the topic?

**Comment by devonwarren** [comment]
> Have you ever wondered what a CMS system based on Django would look like? We are going to go into the basics of what Wagtail is and how it compares with vanilla Django

**Comment by mblayman** [comment]
@devonwarren Are you still good to talk on Wagtail next week?

**Comment by devonwarren** [comment]
@mblayman Yes sir, I'll be there!

**Comment by mblayman** [comment]
@devonwarren, thanks for speaking last night! Could you make your presentation public somehow so I could share a link with the group? Thanks dude.

**Comment by devonwarren** [comment]
@mblayman sure thing, here's the link- https://docs.google.com/presentation/d/1yQZvXwLqSFthUEYkxrK2yJ1pJ1jdmPBoNxp0fXSELAA/edit?usp=sharing
