### ISSUE TITLE
Django overview

### ISSUE THREAD

**Issue by mblayman** [python-frederick/talks#6]
This topic would be an introduction to Django and explain views, templates, and URLs.

**Comment by mblayman** [comment]
@devonwarren Do you have any interest in giving a talk on Django? It looks like it might be the topic for the April meetup on 4/13.

No worries if you don't want to. I know you're a Django user but I know that not everyone wants to give talks.

**Comment by devonwarren** [comment]
@mblayman Yeah, that's something I could totally support!

**Comment by mblayman** [comment]
I've added this one to the calendar for 4/13. http://www.meetup.com/python-frederick/events/229122778/

If you want to bounce ideas off of me for the talk, I'd be happy to contribute. I know a fair bit about Django now too. :smile:

**Comment by mblayman** [comment]
Thanks for the talk and posting the material @devonwarren!
