### ISSUE TITLE
Python and Big Data

### ISSUE THREAD

**Issue by mblayman** [python-frederick/talks#9]
How does Python do Big Data kinds of tasks? What tools are available?

**Comment by patrickpierson** [comment]
@tlpinney is a big data nut.  I pinnged him and he mentioned pyspark and this http://www.slideshare.net/BenjaminBengfort/fast-data-analytics-with-spark-and-python

He might be interested in doing a talk.

**Comment by tlpinney** [comment]
Hey, 
@mblayman @patrickpierson 

I could do a brief overview of Spark, Pandas, Jupyter/IPython Notebook, and ElasticMapReduce and show some example uses.

**Comment by mblayman** [comment]
@tlpinney That sounds great. Would you be able to give such a talk on 5/11? @patrickpierson is doing the talk for March and I think we'll pull a talk for April from the poll that I put out on the meetup site (which is looking more and more like we'll talk about Django). That leaves May as the next open slot.

**Comment by tlpinney** [comment]
@mblayman 5/11 works for me. Thanks!

**Comment by patrickpierson** [comment]
:+1:

**Comment by mblayman** [comment]
I've added this event to the calendar for 5/11. http://www.meetup.com/python-frederick/events/229122911/

**Comment by mblayman** [comment]
@tlpinney thanks for the talk yesterday. Could you ping me once you've committed your presentation material to the talks repo? Once it's up, I can send out a note to the mailing list.

**Comment by tlpinney** [comment]
@mblayman I'll ping you when its up. Should be tonight. Thanks.

**Comment by tlpinney** [comment]
@mblayman I put in a pull request for the talk. https://github.com/python-frederick/talks/pull/19
Thanks!

**Comment by patrickpierson** [comment]
merged.  awesome stuff @tlpinney.  Closing issue.
